export const CONTENT_REQUEST = 'CONTNET_REQUEST';
export const CONTENT_RECEIVED = 'CONTNET_RECEIVED';
export const INITIALIZE_QUIZ = 'INITIALIZE_QUIZ';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const ADVANCE_QUIZ = 'ADVANCE_QUIZ';
