export const CONTENT_REQUEST = 'CONTENT_REQUEST';
export const CONTENT_RECEIVED = 'CONTENT_RECEIVED';
export const UPDATE_TOTAL_SCORE = 'UPDATE_TOTAL_SCORE';
export const ADD_VALUES_TO_LEADERBOARD = 'ADD_VALUES_TO_LEADERBOARD';
