export const CONTENT_REQUEST = 'CONTENT_REQUEST';
export const CONTENT_RECEIVED = 'CONTENT_RECEIVED';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_TOTAL_SCORE = 'UPDATE_TOTAL_SCORE';
export const UPDATE_QUESTION_INDEX = 'UPDATE_QUESTION_INDEX';
